### ISSUE TITLE
Git - make it possible to push to a different branch

### ISSUE THREAD

**Issue by muryoh** [researchgate/gradle-release#113] opened 2015-06-24 19:49 UTC
Hi!

Great work with the plugin. I love the idea and I am almost able to use it as expected.

We're using gerrit - which implies that commits should not be pushed to the branch directly, but to a magic one that gerrit recognizes as one that needs to be reviewed.

For example, one does not push to 'master' but to 'refs/for/master', even if the branch is actually 'master' on the local git repository.

This is currently hard to achieve as the current implementation forces you either:
- push to the current branch
- push to master
- push to 'requireBranch'

**Comment by muryoh** [comment] 2015-06-24 19:52
I would like to add the possibility to set a 'pushToBranch' option to the existing GitAdapter and will most probably submit a PR for this. Does that seem reasonable?

Cheers

**Comment by danez** [comment] 2015-06-24 20:30
Sounds good.

**Comment by radarsh** [comment] 2015-08-10 11:45
Hasn't this been fixed? I just can't seem to get the plugin to push to any branch other than master.

```
git {
    requireBranch = 'not-master'
    pushToRemote = 'origin'
    pushToCurrentBranch = true
}
```

Always stumps me with the below exception.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':initScmAdapter'.
> Current Git branch is "not-master" and not "master".
```

**Comment by danez** [comment] 2015-08-10 12:06
Are you using it like that in your build.gradle?

It should be 
```
release {
    git {
        requireBranch = 'not-master'
        pushToRemote = 'origin'
        pushToCurrentBranch = true
    }
}
```

**Comment by radarsh** [comment] 2015-08-10 12:07
Yes it is within the release DSL. My example was just an excerpt.

**Comment by danez** [comment] 2015-08-10 12:22
I will try to reproduce

**Comment by radarsh** [comment] 2015-08-10 13:46
If it helps, we have a multi-project Gradle setup.

```
parent/
    child-1/
        build.gradle
    settings.gradle
    build.gradle
```
Our build.gradle looks like:

```
import java.util.regex.Matcher

plugins {
    id 'net.researchgate.release' version '2.2.0'
}

subprojects {
    apply plugin: 'groovy'
    apply plugin: 'net.researchgate.release'

    release {
        failOnCommitNeeded = true
        failOnPublishNeeded = true
        failOnSnapshotDependencies = true
        failOnUnversionedFiles = true
        failOnUpdateNeeded = true
        revertOnFail = true
        preCommitText = ''
        preTagCommitMessage = '[Gradle Release Plugin] - pre tag commit: '
        tagCommitMessage = '[Gradle Release Plugin] - creating tag: '
        newVersionCommitMessage = '[Gradle Release Plugin] - new version commit: '
        tagTemplate = '${version}'
        versionPropertyFile = 'gradle.properties'
        versionProperties = []
        buildTasks = ['build']
        versionPatterns = [
            /(\d+)([^\d]*$)/: { Matcher m, Project p -> m.replaceAll("${(m[0][1] as int) + 1}${m[0][2]}") }
        ]
        scmAdapters = [
            net.researchgate.release.GitAdapter
        ]

        git {
            requireBranch = 'develop'
            pushToRemote = 'origin'
            pushToCurrentBranch = false
        }
    }
}
```

When I execute `./gradlew release` from inside the parent directory, I get the above error. Also, I am on git branch `develop`.

**Comment by radarsh** [comment] 2015-08-10 14:04
Just saw the [section on multi project builds](https://github.com/researchgate/gradle-release#multi-project-builds).

I could workaround this limitation by extracting the release plugin configuration out of the subprojects section.

```
import java.util.regex.Matcher

plugins {
    id 'net.researchgate.release' version '2.2.0'
}

apply plugin: 'net.researchgate.release'

release {
    failOnCommitNeeded = true
    failOnPublishNeeded = true
    failOnSnapshotDependencies = true
    failOnUnversionedFiles = true
    failOnUpdateNeeded = true
    revertOnFail = true
    preCommitText = ''
    preTagCommitMessage = '[Gradle Release Plugin] - pre tag commit: '
    tagCommitMessage = '[Gradle Release Plugin] - creating tag: '
    newVersionCommitMessage = '[Gradle Release Plugin] - new version commit: '
    tagTemplate = '${version}'
    versionPropertyFile = 'gradle.properties'
    versionProperties = []
    buildTasks = ['build']
    versionPatterns = [
        /(\d+)([^\d]*$)/: { Matcher m, Project p -> m.replaceAll("${(m[0][1] as int) + 1}${m[0][2]}") }
    ]
    scmAdapters = [
        net.researchgate.release.GitAdapter
    ]

    git {
        requireBranch = 'develop'
        pushToRemote = 'origin'
        pushToCurrentBranch = false
    }
}

subprojects {
    apply plugin: 'groovy'
}
```

**Comment by danez** [comment] 2015-08-10 17:17
Ah okay great. Yes currently the only valid way of applying the release plugin is in the parent project. There is a PR that is going to change this behavior soon. #116 

I close this issue for now, as soon as you have a PR just submit it. @muryoh

**Closed by danez** 2015-08-10 17:17 UTC

**Comment by muryoh** [comment] 2015-10-06 11:43
Push a PR for it: https://github.com/researchgate/gradle-release/pull/140
Although I did do it slightly differently as instead of pushing to a different branch it is relying on a branch prefix.
I figured it would be more strict to keep the idea of pushing to a current branch but to only introduce the required prefix

Let me know what you think

Cheers
