### ISSUE TITLE
Composite build not supported

### ISSUE THREAD

**Issue by B-hamza** [researchgate/gradle-release#383] opened 2023-11-07 13:10 UTC
Using build-convention plugins ii have the error with the release 
showing : 
Cannot include build 'build-logic-conventions' in build ':com.project-release'. This is not supported yet.

My parent gradle.kts release conf 

```
configure<ReleaseExtension> {
    ignoredSnapshotDependencies.set(listOf("net.researchgate:gradle-release"))
    preTagCommitMessage.set("[gradle-release-plugin] prepare release ")
    newVersionCommitMessage.set("[gradle-release-plugin] prepare for next development iteration ")
    with(git) { requireBranch.set("") }
}
```

i hava two subproject 
my Java app and the my composite build 

my root settings.kts 

```
includeBuild("build-logic-conventions")
include("app")
```

**Comment by IRus** [comment] 2024-05-13 05:58
@B-hamza Is this duplicate of https://github.com/researchgate/gradle-release/issues/304?

**Comment by Hillkorn** [comment] 2024-07-08 06:25
As mentioned by @IRus 
Duplicate of #304

**Closed by Hillkorn** 2024-07-08 06:25 UTC
Labels: duplicate
