### ISSUE TITLE
Executor.exec() ignores the passed 'env' value if the system already has an envar with such name

### ISSUE THREAD

**Issue by ddimtirov** [researchgate/gradle-release#135] opened 2015-09-16 04:59 UTC
Came across [this line](https://github.com/researchgate/gradle-release/blob/master/src/main/groovy/net/researchgate/release/cli/Executor.groovy#L32 
) while I was reading the code - it maybe an intended behaviorm, but as it is a bit counterintuitive it is worth to spend a few mins to clarify.

When env vars are specified as key/value params to `Executor.execute()` they will be clobbered by the system environment. 

I.e. if we do `executor.exec('cmd', '/c', 'gradle', 'build', env: [JAVA_OPTS: '-Xmx128m'] )`, our JAVA_OPTS will be used when there is no system provided env var but ignored if `%JAVA_OPTS%` already exist.

If that was the intended behavior, a more intuitive name for such a param would be "envDevaults" - when I pass a param called "env" I expect that this will be the environment that is actually used.

**Comment by danez** [comment] 2015-09-16 10:02
I think you are right, the two maps of variables are merged in the wrong order. I'm currently on vacation and will have a look next week. Feel free to create a pull request and correct the behavior.

**Comment by townsfolk** [comment] 2015-09-17 20:37
Actually, this might have been done on purpose. One situation I can see where you might want the System ENV options to override build script options is so you can hard-code sensible defaults in the build script, but override them (say on a ci environment) through the use of System ENV variables.

**Comment by danez** [comment] 2015-09-19 20:29
But the only place we use it, is for the svn adapter to set the LC_* messages. And in this case I think the variables in code should have precedence.

**Comment by townsfolk** [comment] 2015-09-20 22:49
@danez That makes sense, and I honestly can't remember if I had the env-merging in the original version or if it was something that was added afterwards - I don't remember ever dealing with env variables in the past though. The current way seems more extensible to me, because otherwise you can't differentiate your build for different environments without modifying your build script. That being said, perhaps extensibility is not correct in a reproducible release process situation like we have here?

@ddimtirov I too never really intended for the exec method to be used outside of the plugin - it was just a common utility all the SCM adapters needed.

**Closed** 2015-09-22 11:37 UTC
