### ISSUE TITLE
add Parameter for username and password when releasing to SVN

### ISSUE THREAD

**Issue by Endron** [researchgate/gradle-release#75] opened 2014-02-10 11:47 UTC
I added the plugin to my build and it works just fine when releasing using gradle on my local computer.
As the next step I tried to create a release plan on our CI server (Atlassian Bamboo) so new releases could easily be created from our ticket system (Atlassian Jira).

Execution of the plugin failed with the following error: 
```
* What went wrong:
Execution failed for task ':checkUpdateNeeded'.
> Running "svn status -q -u" produced an error: [svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Unable to connect to a repository at URL ****
svn: E215004: No more credentials or we tried too many times.
Authentication failed]
```

Currently in the docomentation I can not find a way to specify username and password for svn. I belive it works locally by using the username and password saved in my current user profile.

**Comment by danez** [comment] 2015-01-28 16:35
duplicate of #80

**Closed by danez** 2015-01-28 16:35 UTC
