### ISSUE TITLE
Wrong content on Release Tag?

### ISSUE THREAD

**Issue by markush81** [researchgate/gradle-release#50] opened 2013-08-30 05:01 UTC
Hi,

i am not sure if i am wrong, but i think the release tag has the wrong content (using SVN).

as an example:

SVN REV 200: has code with version 1.2-SNAPSHOT
-> the plugin changes to 1.2 and preTags, so we have SVN REV 201
-> the plugin builds the project and has artifacts of version 1.2
-> the plugin does the release tag but with SVN REV 200 instead of REV 201
-> the plugin does change the version to 1.3-SNAPSHOT and commits to REV 202

The issue from my perspective is, that the code living on the tag is not the code which has been release, but the code before the release.

I guess when doing the preTagCommit the result SVN Rev has to be remembered as svnRevision

Cheers, markus

**Comment by danez** [comment] 2015-01-27 17:42
duplicate of #48

**Closed by danez** 2015-01-27 17:42 UTC
