### ISSUE TITLE
'build' and 'publish' marked as "UP-TO-DATE" mistakenly?

### ISSUE THREAD

**Issue by zhen-lu** [researchgate/gradle-release#334] opened 2020-06-08 06:42 UTC
build.gradle have these lines:

`
plugins {
    id 'maven-publish'
    id "net.researchgate.release" version "$gradleReleaseVersion"
...
}
    afterReleaseBuild.dependsOn publish
...

release {
    buildTasks = ['build']
...
`

cmd: ./gradlew --info --rerun-tasks release

The gradle process completed with success but the build task 'build' and publishing task 'publish' both marked as UP-TO-DATE and has no actions.

`> Task :paylater-collections:paylater-collections:build UP-TO-DATE
Skipping task ':paylater-collections:paylater-collections:build' as it has no actions.
:paylater-collections:paylater-collections:build (Thread[Execution worker for ':paylater-collections:paylater-collections' Thread 11,5,main]) completed. Took 0.0 secs.`

gradle version: 6.5
gradleReleaseVersion: 2.8.1

**Comment by F43nd1r** [comment] 2020-07-07 22:38
I've had a similar issue and several other, which I fixed in [my modernized fork of this plugin](https://github.com/F43nd1r/gradle-release). You can try if it solves your issue as well.

**Comment by Vampire** [comment] 2020-08-08 16:56
And where is your problem if everything went well?
Both those tasks are lifecycle tasks whose only purpose is to depend on other tasks that do the actual work.
This also has nothing to do with this plugin as they are standard lifecycle tasks by Gradle itself.
It is absolutely normal and expected that those tasks do not have any actions and thus are always skipped.

**Comment by zhen-lu** [comment] 2020-08-10 15:55
> And where is your problem if everything went well?
> Both those tasks are lifecycle tasks whose only purpose is to depend on other tasks that do the actual work.
> This also has nothing to do with this plugin as they are standard lifecycle tasks by Gradle itself.
> It is absolutely normal and expected that those tasks do not have any actions and thus are always skipped.

Thanks for the reply. The problem here is that those are so called build tasks and are expected to be executed rather than skipped. 've tried to be more explicit by adding:
`release {
buildTasks = ['build']`
But still the tasks got skipped causing in-complete releases

**Comment by zhen-lu** [comment] 2020-08-10 15:58
> my modernized fork of this plugin

Thanks for the reply. The fork is in Kotlin. Does it require the project to be in Kotlin as well?

**Comment by F43nd1r** [comment] 2020-08-10 16:32
> Thanks for the reply. The fork is in Kotlin. Does it require the project to be in Kotlin as well?

No, groovy should still work. I've started writing this fork to support kotlin build scripts, but then I reworked a lot of other things too. So it is very much kotlin first, but not exclusive. E.g. I've just tested this configuration with groovy
```groovy
release {
    revertOnFail = false
    git {
        requireBranch = 'master'
    }
}
```

**Comment by Vampire** [comment] 2020-08-10 19:06
> Thanks for the reply. The problem here is that those are so called build tasks and are expected to be executed rather than skipped. 've tried to be more explicit by adding:
release { buildTasks = ['build']
But still the tasks got skipped causing in-complete releases

You still misunderstand.
Whatever you do to the task `build`, it has no actions itself and thus will always be up-to-date.
And that is absolutely ok and correct, as there is nothing to do for the task itself.
That the task itself is up-to-date does **not** mean that its dependencies do not get executed.
Actually this is the wohle purpose of those lifecycle tasks, to depend on other tasks that do the actual work.
If your release is incomplete, then this most likely is not caused by the `build` task being up-to-date as that is absolutely normal and expected, but you should investigate what else is actually wrong in your build scripts. ;-)

**Comment by zhen-lu** [comment] 2020-08-10 19:58
> > Thanks for the reply. The problem here is that those are so called build tasks and are expected to be executed rather than skipped. 've tried to be more explicit by adding:
> > release { buildTasks = ['build']
> > But still the tasks got skipped causing in-complete releases
> 
> You still misunderstand.
> Whatever you do to the task `build`, it has no actions itself and thus will always be up-to-date.
> And that is absolutely ok and correct, as there is nothing to do for the task itself.
> That the task itself is up-to-date does **not** mean that its dependencies do not get executed.
> Actually this is the wohle purpose of those lifecycle tasks, to depend on other tasks that do the actual work.
> If your release is incomplete, then this most likely is not caused by the `build` task being up-to-date as that is absolutely normal and expected, but you should investigate what else is actually wrong in your build scripts. ;-)

Interesting. Then to actually have build/publish executed I'll probably need to run something like `./gradlew --info --profile --rerun-tasks build publish release` instead of `./gradlew --info --profile release` with build and publish as build tasks?

**Comment by Vampire** [comment] 2020-08-10 21:02
I have no idea about your task dependencies.
For me, I only have to do `./gradlew release` to create a release and the only build task I have configured is actually `build`.
But I know my builds are configured properly.

**Comment by zhen-lu** [comment] 2020-08-11 02:22
> I have no idea about your task dependencies.
> For me, I only have to do `./gradlew release` to create a release and the only build task I have configured is actually `build`.
> But I know my builds are configured properly.

In my case both `build` and `publish` tasks are configured and do get called; the problem is that build task 'build' and publishing task 'publish' both marked as UP-TO-DATE and has no actions.

**Comment by Vampire** [comment] 2020-08-11 07:57
I'm going to repeat it one last time for you, then I just start ignore mode.
That both are marked as up-to-date and have no actions is absolutely normal and expected.
This is **not** your problem.
It is the same for my projects and most other Gradle projects out there.
If you really care that much, just add some action like `tasks.build { doLast { logger.warn('I am useless') } }`.
But that will change nothing at all besides that you don't get the up-to-date string displayed.

**Comment by F43nd1r** [comment] 2020-08-13 21:50
My problem was that tasks attached to publish weren't run. That problem is fixed in my fork. It sounds like I mistakenly assumed this was caused by the publish task being marked up-to-date.

**Comment by zhen-lu** [comment] 2020-08-14 01:23
> My problem was that tasks attached to publish weren't run. That problem is fixed in my fork. It sounds like I mistakenly assumed this was caused by the publish task being marked up-to-date.

This sound exactly like the problem I'm facing. Those jobs were marked up-to-date and thus no actions, i.e. not published. If you have it fixed in your fork sounds like worth checking out indeed

**Comment by zhen-lu** [comment] 2020-08-20 17:37
> > Thanks for the reply. The fork is in Kotlin. Does it require the project to be in Kotlin as well?
> 
> No, groovy should still work. I've started writing this fork to support kotlin build scripts, but then I reworked a lot of other things too. So it is very much kotlin first, but not exclusive. E.g. I've just tested this configuration with groovy
> 
> ```groovy
> release {
>     revertOnFail = false
>     git {
>         requireBranch = 'master'
>     }
> }
> ```

Gave this fork a try and the buildTasks are not even triggered. Tried the default and specify explicitly with
`release {
    buildTasks = ['build']
}`
The 'build' task is not triggered at all ...

**Comment by F43nd1r** [comment] 2020-08-20 17:42
Please open an issue in the forks issue tracker to discuss it, so we don't spam this repository with unrelated content.
If you do, please share more details about your build. As I said, it is working in my minimal example. Which means we'll have to find what you're doing differently.

**Comment by zhen-lu** [comment] 2020-08-20 17:50
> Please open an issue in the forks issue tracker to discuss it, so we don't spam this repository with unrelated content.
> If you do, please share more details about your build. As I said, it is working in my minimal example. Which means we'll have to find what you're doing differently.

How to open an issue on that fork? tried to look for the `issues` tab but couldn't find it.

**Comment by F43nd1r** [comment] 2020-08-20 17:52
apparently github disables them by default on forks. Fixed it.

**Comment by zhen-lu** [comment] 2020-08-20 18:03
> apparently github disables them by default on forks. Fixed it.

Thanks; submitted: https://github.com/F43nd1r/gradle-release/issues/1

**Comment by Hillkorn** [comment] 2020-09-30 11:30
As written in F43nd1r#1 the problem could have been fixed by letting the rootProject build task depend on the sub project build tasks. There is a difference between running `gradle build` and having a task with a dependency to the build task as the dependency only triggers the task it is related to while `gradle build` will run build in every project it finds it.

In your build.gradle you could have added the following at the end
```
project.subprojects.each { it.parent.build.dependsOn it.tasks.build }
```

And to really test your build task and what it exactly does you have to run `gradle :build` which will only run the rootProject's build task and not all of them automatically.
Only found https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:locating_tasks example 6 that mentions it a bit.

**Closed by Hillkorn** 2020-09-30 11:30 UTC
