### ISSUE TITLE
Wrong revision when tagging

### ISSUE THREAD

**Issue by mjke87** [researchgate/gradle-release#71] opened 2013-12-18 09:35 UTC
*Setup*
Gradle version: 1.9
Release plugin version: 1.2
SCM: SVN

*Problem*
When releasing the tag is created using the wrong revision, using subversion. It is created from the initially checked-out revision, the one before the unsnapshot version was committed. This leads to a snapshot version in the tag.

*Build log*
```
...
At revision 23461
[Gradle] - Launching build.
...
:preTagCommit
Executing task ':preTagCommit' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
 >>> Running [svn, ci, -m, [Gradle Release Plugin] - pre tag commit:  '2.4.2'.]
 >>> Running [svn, ci, -m, [Gradle Release Plugin] - pre tag commit:  '2.4.2'.]: [Sende          gradle.properties
Übertrage Daten .
Revision 23462 übertragen.
...
:createReleaseTag
Executing task ':createReleaseTag' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Running "svn cp https://<my-svn-url>/<project>/trunk@23461 https://<my-svn-url>/<project>/tags/2.4.2 -m [Gradle Release Plugin] - creating tag:  '2.4.2'."
Running "svn cp https://<my-svn-url>/<project>/trunk@23461 https://<my-svn-url>/<project>/tags/2.4.2 -m [Gradle Release Plugin] - creating tag:  '2.4.2'.": [
Revision 23463 übertragen.
...
:commitNewVersion
Executing task ':commitNewVersion' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
 >>> Running [svn, ci, -m, [Gradle Release Plugin] - new version commit:  '2.4.3-SNAPSHOT'.]
 >>> Running [svn, ci, -m, [Gradle Release Plugin] - new version commit:  '2.4.3-SNAPSHOT'.]: [Sende          gradle.properties
Übertrage Daten .
Revision 23464 übertragen.
```

Note the 23461 revision used for tagging. I would have expected the revision 23462 which includes the unsnapshot version commit.

*Fix*
I temporarily fixed the problem by incrementing the revision number stored in the `releaseSvnRev` property by one, before the `createReleaseTag` task is executed.

Regards,
Mike

**Comment by danez** [comment] 2015-01-27 17:41
duplicate of #48

**Closed by danez** 2015-01-27 17:41 UTC
